// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLGIhER5Ih6POeJFaYT_mD1IKmDFM_QeQ',
    appId: '1:1053100621446:web:45213efbbe85b734ab5b07',
    messagingSenderId: '1053100621446',
    projectId: 'cookbook-flutter-54d74',
    authDomain: 'cookbook-flutter-54d74.firebaseapp.com',
    storageBucket: 'cookbook-flutter-54d74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkEkF2gtsxQNKRzZE0o8giokxsGQef_RE',
    appId: '1:1053100621446:android:cc0b12e78120dd0fab5b07',
    messagingSenderId: '1053100621446',
    projectId: 'cookbook-flutter-54d74',
    storageBucket: 'cookbook-flutter-54d74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvz4yqfSNGD7_ObL9WXzKvog6LwjzbxTc',
    appId: '1:1053100621446:ios:0f056daefa373443ab5b07',
    messagingSenderId: '1053100621446',
    projectId: 'cookbook-flutter-54d74',
    storageBucket: 'cookbook-flutter-54d74.appspot.com',
    iosBundleId: 'com.example.cookbook',
  );
}
